### ISSUE TITLE
パッと思ったこと

### ISSUE THREAD

**Issue by mimorisuzuko** [fmsuvM/GitStudy#2]
パッと見て思ったことを書いた．必ずしも真ではないので参考程度に．

**全体**

シンプルに書く．ルーティンを分かりやすく．途中でごちゃごちゃした説明を挟まない（ごちゃごちゃしたものは後述の付録にいれるといいと思う）．
1. GitHub登録
2. レポジトリ作成
3. コミット
4. コード更新
5. 3に戻る

ぐらい？

**使うもの統一する**

CUIなのかGUIなのか決めちゃう（説明しやすい or 対象者が分かりやすい方）．レポジトリ名とかもこっちで決めちゃう．「今回は，xxxとする」とか．

この辺で「うーん　どっちにしようかなー」とか「なんて名前にしようかなー」とかで時間食ってると勿体ない．

**付録と本編に分ける**

例えば，「BitBucketと何が違うねん」は付録．知らなくても死なないモノは付録．Issueとかも付録かなあ．本編は実際に講義で最低限説明するもの（また，後でB1が読み返しても苦労しないもの）にする．

**無駄な英語使わない**

codeとか（表記揺れしてるし）．

**タイトルのイタリック体ダサい**

ダサい．ウケる．

**Comment by mimorisuzuko** [comment]
あとちょいちょい入る罫線いらない

**Comment by tkdsym2** [comment]
全体的に直しました.
